sudo: required
dist: xenial
language: cpp

env:
  global:
    # ---- TODO: Enter values ----
    - CONAN_USERNAME="TODO_ENTER_PACKAGE_USERNAME"
    - CONAN_PACKAGE_NAME="TODO_ENTER_PACKAGE_NAME"

conan-buildsteps: &conan-buildsteps
  before_install:
    # use this step if you desire to manipulate CONAN variables programmatically
    # dummy to overwrite default build steps
    - true
  install:
    - chmod +x ./conan/ci/install.sh
    - ./conan/ci/install.sh
  script:
    - chmod +x ./conan/ci/build.sh
    - ./conan/ci/build.sh
   # the following are dummies to overwrite default build steps
  before_script:
    - true
  after_success:
    - true
  if: tag IS present
conan-linux: &conan-linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker
  <<: *conan-buildsteps
conan-osx: &conan-osx
  os: osx
  language: generic
  <<: *conan-buildsteps

matrix:
  include:
    # ---- TODO: PLACE HERE ALL EXISTING BUILD JOBS ----
    #
    # Conan testing and uploading
    - compiler: gcc
      env: CONAN=True
      language: python
      python: "3.6"
      before_install:
        - pip install -U pip
      install:
        - pip install conan
      before_script:
        - pip --version
        - conan --version
      script:
        - CONAN_FULL_REFERENCE=${CONAN_PACKAGE_NAME}/master@${CONAN_USERNAME}/testing
        - conan create . ${CONAN_FULL_REFERENCE} --build --test-folder "conan/test_package"
      # ---- TODO: Include the following build step ONLY for a master version recipe upload and testing (no packages) ----
      # ---- TODO: Remove after_success entirely if you don't want a master recipe version uploaded ----
      after_success:
        # If this build is NOT triggered by a pull request; AND got triggered by either a tag OR push to master
        # and the following environment variables are set:
        #   CONAN_UPLOAD - a reference to the Conan repository e.g. https://bintray.com/google/conan
        #   CONAN_LOGIN_USERNAME - user for the upload e.g. upload_bot_username
        #   CONAN_PASSWORD - password for the CONAN_LOGIN_USERNAME; for Bintray this is the API key
        # then upload the new recipe version to the Conan repository.
        #
        # For the tag pushes we are using for the
        #   version the tag name, removing the "v"
        #   channel "stable"
        # For master pushes we are using for the
        #   version simply "master"
        #   channel "testing"
        - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" && -n "${CONAN_UPLOAD}" && -n "${CONAN_LOGIN_USERNAME}" && -n "${CONAN_PASSWORD}" ]]; then
            conan remote add ${CONAN_PACKAGE_NAME} ${CONAN_UPLOAD} --insert;
            conan remote list;

            conan user -p "${CONAN_PASSWORD}" -r benchmark "${CONAN_LOGIN_USERNAME}";
            conan upload --force -r ${CONAN_PACKAGE_NAME} --retry 3 --retry-wait 10 --confirm "${CONAN_FULL_REFERENCE}";
          fi;
      if: NOT tag IS present
    # ---- TODO: If neccessary adjust the following configurations to your upstream project support -----
    - <<: *conan-linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49
    - <<: *conan-linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
    - <<: *conan-linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6
    - <<: *conan-linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
    - <<: *conan-linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *conan-linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39
    - <<: *conan-linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40
    - <<: *conan-linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50
    - <<: *conan-linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60
    - <<: *conan-linux
      env: CONAN_CLANG_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/clang7
    - <<: *conan-osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3
    - <<: *conan-osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1
    - <<: *conan-osx
      osx_image: xcode9
      env: CONAN_APPLE_CLANG_VERSIONS=9.0
    - <<: *conan-osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1
    - <<: *conan-osx
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0

# ---- TODO: Place here all existing default build steps ----
